title: <p align="center"> Omar KAMI </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/omar-kami-6a3816201/">LinkedIn</a> |
  <a href="https://github.com/omarkami007">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing an Industrial Management engineering degree at EMINES-UM6P, Morocco.
  I am a Data Science and Machine Learning enthusiast, and I am particularly interested in automation.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
